use std::{
    env,
    error::Error,
    ffi::OsStr,
    fs,
    path::{Path, PathBuf},
};

const GONKA_REPOSITORY: &str = "https://github.com/gonka-ai/gonka";
const GONKA_COMMIT: &str = "379bebced638aeb5e6077bfd51c986f898443832";
const GENERATED_HEADER: &str = "// @generated by tools/proto-gen. DO NOT EDIT.\n\
// Source: https://github.com/gonka-ai/gonka\n\
// Source commit: 379bebced638aeb5e6077bfd51c986f898443832\n\n";
const GENERATED_MODULE_LINTS: &str = concat!(
    "#![allow(\n",
    "    clippy::doc_lazy_continuation,\n",
    "    clippy::enum_variant_names,\n",
    "    clippy::module_inception\n",
    ")]\n\n"
);
const REQUIRED_SYMBOLS: &[&str] = &[
    "pub struct QueryGetCurrentEpochRequest",
    "pub struct QueryGetCurrentEpochResponse",
    "pub struct QueryListClaimRecipientsRequest",
    "pub struct QueryListClaimRecipientsResponse",
    "pub struct ClaimRecipientEntry",
    "pub struct QueryEpochPerformanceSummaryByParticipantRequest",
    "pub struct QueryEpochPerformanceSummaryByParticipantResponse",
    "pub struct EpochPerformanceSummary",
    "pub struct QueryTotalVestingAmountRequest",
    "pub struct QueryTotalVestingAmountResponse",
    "pub struct Coin",
];

fn main() -> Result<(), Box<dyn Error>> {
    let tool_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = tool_dir
        .parent()
        .and_then(Path::parent)
        .ok_or("tools/proto-gen must be located below the repository root")?;
    let proto_root = repo_root.join("packages/gonka-proto/proto/vendor");
    let generated_dir = repo_root.join("packages/gonka-proto/src/generated");
    let staging_dir = tool_dir.join("target/generated-staging");

    if !proto_root.is_dir() {
        return Err(format!("missing vendored proto directory: {}", proto_root.display()).into());
    }

    recreate_dir(&staging_dir)?;

    let mut protos = collect_proto_files(&proto_root)?;
    protos.sort();
    if protos.is_empty() {
        return Err("vendored proto directory contains no .proto files".into());
    }

    // prost-build uses the protoc binary named by PROTOC. The binary comes
    // from a pinned Rust crate, so no machine-wide protoc installation is used.
    env::set_var("PROTOC", protoc_bin_vendored::protoc_bin_path()?);

    let mut config = prost_build::Config::new();
    config.out_dir(&staging_dir);
    config.include_file("mod.rs");
    config.compile_protos(&protos, &[proto_root])?;

    let generated_files = collect_rust_files(&staging_dir)?;
    if generated_files.is_empty() {
        return Err("prost-build produced no Rust files".into());
    }

    let combined = generated_files
        .iter()
        .map(fs::read_to_string)
        .collect::<Result<Vec<_>, _>>()?
        .join("\n");
    for required in REQUIRED_SYMBOLS {
        if !combined.contains(required) {
            return Err(
                format!("generated bindings are missing required symbol: {required}").into(),
            );
        }
    }

    recreate_dir(&generated_dir)?;
    for source in generated_files {
        let file_name = source
            .file_name()
            .ok_or_else(|| format!("generated path has no file name: {}", source.display()))?;
        let mut body = fs::read_to_string(&source)?;
        let lint_header = if file_name == "mod.rs" {
            body.push_str("\npub mod provenance;\n");
            GENERATED_MODULE_LINTS
        } else {
            ""
        };
        fs::write(
            generated_dir.join(file_name),
            format!("{GENERATED_HEADER}{lint_header}{body}"),
        )?;
    }
    fs::write(
        generated_dir.join("provenance.rs"),
        format!(
            "{GENERATED_HEADER}/// Repository used to generate the committed protobuf bindings.\n\
             pub const SOURCE_REPOSITORY: &str = {GONKA_REPOSITORY:?};\n\
             /// Exact Gonka source revision used to generate the committed bindings.\n\
             pub const SOURCE_COMMIT: &str = {GONKA_COMMIT:?};\n"
        ),
    )?;

    println!("Generated Gonka protobuf bindings");
    println!("  source: {GONKA_REPOSITORY}@{GONKA_COMMIT}");
    println!("  proto files: {}", protos.len());
    println!("  output: {}", generated_dir.display());
    Ok(())
}

fn collect_proto_files(root: &Path) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    collect_files_with_extension(root, "proto")
}

fn collect_rust_files(root: &Path) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    let mut files = collect_files_with_extension(root, "rs")?;
    files.sort();
    Ok(files)
}

fn collect_files_with_extension(
    root: &Path,
    extension: &str,
) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    let mut result = Vec::new();
    let mut pending = vec![root.to_path_buf()];

    while let Some(directory) = pending.pop() {
        for entry in fs::read_dir(directory)? {
            let path = entry?.path();
            if path.is_dir() {
                pending.push(path);
            } else if path.extension() == Some(OsStr::new(extension)) {
                result.push(path);
            }
        }
    }

    Ok(result)
}

fn recreate_dir(path: &Path) -> Result<(), Box<dyn Error>> {
    if path.exists() {
        fs::remove_dir_all(path)?;
    }
    fs::create_dir_all(path)?;
    Ok(())
}
